Models/ErrorViewModel.cs
namespace PRELIM_E3_Assignment_FugenAira_BSIT_32E1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/School.cs
namespace PRELIM_E3_Assignment_FugenAira_BSIT_32E1.Models
{
    public class School
    {
        public int Schedule { get; set; }
        public String Day { get; set; }
        public int Time { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PRELIM_E3_Assignment_FugenAira_BSIT_32E1.Models;
using System.Diagnostics;

namespace PRELIM_E3_Assignment_FugenAira_BSIT_32E1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
     
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SchoolController.cs
using Microsoft.AspNetCore.Mvc;
using PRELIM_E3_Assignment_FugenAira_BSIT_32E1.Models;
using System.Diagnostics;

namespace PRELIM_E3_Assignment_FugenAira_BSIT_32E1.Controllers
{
    public class SchoolController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public SchoolController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    h1 {
        font-family: 'Comic Sans MS';
        text-align: center;
        margin-top: 250px;
    }
    p {
        font-family: 'Comic Sans MS';
        font-size: 20px;
        margin-top: 20px;
    }
    .nav-links {
        font-family: 'Comic Sans MS';
        background-color: whitesmoke;
        box-shadow: 5px 5px 7px white rgba(0, 0, 0, 0.3);
    }
    .nav-links:hover{
        background-color: deeppink;
    }
</style>
<div class="text-center">
    <h1 class="display-4">Hi! I'm Aira Fugen</h1>
    <p>I'm 3rd year college in Lyceum of Alabang. My course is Bachelor of Science in Information Technology and I belong to BSIT32E1. </p>
    
</div>

Views/School/Index.cshtml
<style>

    h1 {
        font-family: 'Comic Sans MS';
        text-align: center;
        margin-top: 50px;
    }

    p {
        font-family: 'Comic Sans MS';
        font-size: 20px;
        margin-top: 20px;
        text-align: center;
    }

    table {
        font-family: 'Comic Sans MS';
        width: 100%;
        border-collapse: collapse;
        margin-top: 70px;
    }

    td {
        border: 1px solid black;
        padding: 20px;
        text-align: center;
        background-color: whitesmoke;
    }

    th {
        border: 1px solid black;
        padding: 5px;
        text-align: center;
        background-color: hotpink;
    }

    .hotpink-bg {
        background-color: hotpink;
    }

    }
</style>
<h1>𝐂𝐎𝐋𝐋𝐄𝐆𝐄 𝐎𝐅 𝐂𝐎𝐌𝐏𝐔𝐓𝐄𝐑 𝐒𝐓𝐔𝐃𝐈𝐄𝐒 𝐒𝐂𝐇𝐄𝐃𝐔𝐋𝐄</h1>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>
            SUBJECT TITLE
        </th>
        <th>
            TEACHER
            </th>
            <th>
            DAY AND TIME
        </th>
    </tr>
    </thead>
    <tbody>
        
        <tr>
            <td>
                IT Elective 3 (FULL STACK)
            </td>
            <td>
                Prof NIÑO FRANCISCO ALAMO
            </td>
            <td>
                SATURDAY 7:00 - 10:00 AM
            </td>

        </tr>

    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRELIM_E3_Assignment_FugenAira_BSIT_32E1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PRELIM_E3_Assignment_FugenAira_BSIT_32E1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-pink bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">𝒜ℱ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link "asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  "asp-controller="School" asp-action="Index">School</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>